### ISSUE TITLE
Starting after clean install, the map is grayed out

### ISSUE THREAD

**Issue by LefterisJP** [Sikorkaio/android-app#13]
If sikorka is started after a clean reinstall then the map is grayed out and does not show anything during the initial sync.

Log can be found [here](https://gist.github.com/LefterisJP/88fd9ead7eae8985711597e5d6be503c).

And some screenshots:

![screenshot_20180124-101316](https://user-images.githubusercontent.com/1658405/35324187-4ddaf818-00f0-11e8-9dc7-34e3de223613.png)

![screenshot_20180124-101001](https://user-images.githubusercontent.com/1658405/35324208-5dc0a714-00f0-11e8-996a-f4921e768e20.png)

**Comment by kelsos** [comment]
@LefterisJP are you still encountering this issue? I can see in the logs that it failed to authorize the maps API key. Did you use your own API key?

**Comment by LefterisJP** [comment]
Yes I have an API key set as pet the guide [here](https://github.com/Sikorkaio/android-app/blob/master/GUIDE/build.md)

**Comment by LefterisJP** [comment]
Okay we figured it out, it was about having the proper app restrictions for the key. As discussed this should also be mentioned in the build guide.
