### ISSUE TITLE
Update to official go-ethereum artifact

### ISSUE THREAD

**Issue by kelsos** [Sikorkaio/android-app#19]
Investigate if the latest go-ethereum artifact has fixed the contract binding issues and if so upgrade to the official release.

**Comment by kelsos** [comment]
Contract binding is still broken as of 1.8.1. Should upgrade the forked version with the upstream 1.8.1 as a base.

**Comment by LefterisJP** [comment]
What do you mean? Is it a contract problem or a geth problem?

**Comment by kelsos** [comment]
@LefterisJP Still getting the same error when binding a contract and attempting to call a contract function. This was the reason I originally created the forked version. There seems to be a merge providing a fix for this so I will have to build from upstream and check it. If merged we should be able to go to the official library in the next version.

**Comment by kelsos** [comment]
This was fixed as of 1.8.2 of go ethereum so there is no need for a custom build of the library.
